#!/bin/bash

. /opt/remnasetup/scripts/common/colors.sh

LANGUAGE_FILE="/opt/remnasetup/.language"

if [ -f "$LANGUAGE_FILE" ]; then
    LANGUAGE=$(cat "$LANGUAGE_FILE")
fi

select_language() {
    if [ -z "$LANGUAGE" ] || [ "$LANGUAGE" != "en" ] && [ "$LANGUAGE" != "ru" ]; then
        while true; do
            clear
            echo -e "${MAGENTA}────────────────────────────────────────────────────────────${RESET}"
            echo -e "${BOLD_CYAN}Select language / Выберите язык:${RESET}"
            echo -e "${BLUE}1) English${RESET}"
            echo -e "${BLUE}2) Русский${RESET}"
            echo -e "${MAGENTA}────────────────────────────────────────────────────────────${RESET}"
            read -p "$(echo -e "${BOLD_CYAN}Enter your choice (1-2) / Введите ваш выбор (1-2):${RESET}") " lang_choice

            case $lang_choice in
                1)
                    LANGUAGE="en"
                    break
                    ;;
                2)
                    LANGUAGE="ru"
                    break
                    ;;
                *)
                    echo -e "${BOLD_RED}Invalid choice. Please select 1 for English or 2 for Russian.${RESET}"
                    echo -e "${BOLD_RED}Неверный выбор. Пожалуйста, выберите 1 для Английского или 2 для Русского.${RESET}"
                    sleep 2
                    ;;
            esac
        done
        echo "$LANGUAGE" > "$LANGUAGE_FILE"
    fi
}

declare -A LANG_STRINGS

# Remnasetup
LANG_STRINGS["en_main_menu"]="Main Menu"
LANG_STRINGS["en_remnawave_menu"]="Remnawave Menu"
LANG_STRINGS["en_remnanode_menu"]="Remnanode Menu"
LANG_STRINGS["en_backup_menu"]="Backup and Restore Menu"
LANG_STRINGS["en_exit"]="Exit"
LANG_STRINGS["en_invalid_choice"]="Invalid choice. Please try again."
LANG_STRINGS["en_installation_complete"]="Installation completed successfully!"
LANG_STRINGS["en_error"]="Error:"
LANG_STRINGS["en_press_enter"]="Press Enter to continue..."
LANG_STRINGS["en_select_option"]="Select menu option"
LANG_STRINGS["en_script_error"]="Script ended with an error"
LANG_STRINGS["en_script_not_found"]="Script not found"
LANG_STRINGS["en_press_any_key"]="Press any key to return to menu..."
LANG_STRINGS["en_exiting"]="Exiting program..."
LANG_STRINGS["en_select_menu_option"]="Select menu option"
LANG_STRINGS["en_root_required"]="This script must be run as root"
LANG_STRINGS["en_directory_not_exist"]="Directory %s does not exist"
LANG_STRINGS["en_file_not_exist"]="File %s does not exist"

LANG_STRINGS["ru_main_menu"]="Главное меню"
LANG_STRINGS["ru_remnawave_menu"]="Меню Remnawave"
LANG_STRINGS["ru_remnanode_menu"]="Меню Remnanode"
LANG_STRINGS["ru_backup_menu"]="Меню резервной копии и восстановления"
LANG_STRINGS["ru_exit"]="Выход"
LANG_STRINGS["ru_invalid_choice"]="Неверный выбор. Попробуйте снова."
LANG_STRINGS["ru_installation_complete"]="Установка успешно завершена!"
LANG_STRINGS["ru_error"]="Ошибка:"
LANG_STRINGS["ru_press_enter"]="Нажмите Enter для продолжения..."
LANG_STRINGS["ru_select_option"]="Выберите пункт меню"
LANG_STRINGS["ru_script_error"]="Скрипт завершился с ошибкой"
LANG_STRINGS["ru_script_not_found"]="Скрипт не найден"
LANG_STRINGS["ru_press_any_key"]="Нажмите любую клавишу для возврата в меню..."
LANG_STRINGS["ru_exiting"]="Выход из программы..."
LANG_STRINGS["ru_select_menu_option"]="Выберите пункт меню"
LANG_STRINGS["ru_root_required"]="Этот скрипт должен быть запущен с правами root"
LANG_STRINGS["ru_directory_not_exist"]="Директория %s не существует"
LANG_STRINGS["ru_file_not_exist"]="Файл %s не существует"

# auto_backup
LANG_STRINGS["en_auto_backup_cleanup_old_crons"]="Cleaning up old backup tasks..."
LANG_STRINGS["en_auto_backup_select_mode"]="Select backup mode (y - once a day, n - every n hours):"
LANG_STRINGS["en_auto_backup_please_answer_yn"]="Please answer y or n"
LANG_STRINGS["en_auto_backup_current_time"]="Current server time: %s"
LANG_STRINGS["en_auto_backup_enter_time"]="Enter automatic backup time (e.g. 23:00):"
LANG_STRINGS["en_auto_backup_invalid_time"]="Invalid time format. Use 24-hour format (e.g.: 23:00)"
LANG_STRINGS["en_auto_backup_enter_interval"]="Enter backup interval in hours (1-23):"
LANG_STRINGS["en_auto_backup_enter_number"]="Please enter a number from 1 to 23"
LANG_STRINGS["en_auto_backup_enter_storage"]="Enter maximum backup storage time in days (default 3):"
LANG_STRINGS["en_auto_backup_use_telegram"]="Do you want to send backup to Telegram bot? (y/n):"
LANG_STRINGS["en_auto_backup_enter_bot_token"]="Enter Telegram bot token:"
LANG_STRINGS["en_auto_backup_enter_chat_id"]="Enter your Telegram chat_id:"
LANG_STRINGS["en_auto_backup_configured"]="Automatic backup configured"
LANG_STRINGS["en_auto_backup_daily_at"]="Backup will run daily at %s"
LANG_STRINGS["en_auto_backup_every_hours"]="Backup will run every %s %s"
LANG_STRINGS["en_auto_backup_storage_days"]="Backups will be stored for %s %s"
LANG_STRINGS["en_auto_backup_telegram_configured"]="Telegram bot sending configured"
LANG_STRINGS["en_auto_backup_enter_password"]="Enter archive password (minimum 8 characters):"
LANG_STRINGS["en_auto_backup_password_short"]="Password must be at least 8 characters long"
LANG_STRINGS["en_auto_backup_press_key"]="Press any key to return to menu..."
LANG_STRINGS["en_auto_backup_cron_not_found"]="Cron is not installed. Installing..."
LANG_STRINGS["en_auto_backup_cron_installed"]="Cron installed and started."
LANG_STRINGS["en_auto_backup_cron_install_failed"]="Failed to install cron. Please install it manually."

LANG_STRINGS["ru_auto_backup_cleanup_old_crons"]="Очистка старых задач резервной копии..."
LANG_STRINGS["ru_auto_backup_select_mode"]="Выберите режим резервной копии (y - раз в сутки, n - каждые n часов):"
LANG_STRINGS["ru_auto_backup_please_answer_yn"]="Пожалуйста, ответьте y или n"
LANG_STRINGS["ru_auto_backup_current_time"]="Текущее время сервера: %s"
LANG_STRINGS["ru_auto_backup_enter_time"]="Введите время авто резервной копии (например 23:00):"
LANG_STRINGS["ru_auto_backup_invalid_time"]="Неверный формат времени. Используйте 24-часовой формат (например: 23:00)"
LANG_STRINGS["ru_auto_backup_enter_interval"]="Введите интервал между резервными копиями в часах (1-23):"
LANG_STRINGS["ru_auto_backup_enter_number"]="Пожалуйста, введите число от 1 до 23"
LANG_STRINGS["ru_auto_backup_enter_storage"]="Введите максимальное время хранения резервной копии в днях (по умолчанию 3):"
LANG_STRINGS["ru_auto_backup_use_telegram"]="Хотите отправлять резервную копию в Telegram-бота? (y/n):"
LANG_STRINGS["ru_auto_backup_enter_bot_token"]="Введите токен Telegram-бота:"
LANG_STRINGS["ru_auto_backup_enter_chat_id"]="Введите ваш chat_id в Telegram:"
LANG_STRINGS["ru_auto_backup_configured"]="Авторезервная копия настроена"
LANG_STRINGS["ru_auto_backup_daily_at"]="Резервная копия будет выполняться ежедневно в %s"
LANG_STRINGS["ru_auto_backup_every_hours"]="Резервная копия будет выполняться каждые %s %s"
LANG_STRINGS["ru_auto_backup_storage_days"]="Резервные копии будут храниться %s %s"
LANG_STRINGS["ru_auto_backup_telegram_configured"]="Настроена отправка в Telegram-бота"
LANG_STRINGS["ru_auto_backup_enter_password"]="Введите пароль для архива (минимум 8 символов):"
LANG_STRINGS["ru_auto_backup_password_short"]="Пароль должен содержать минимум 8 символов"
LANG_STRINGS["ru_auto_backup_press_key"]="Нажмите любую клавишу для возврата в меню..."
LANG_STRINGS["ru_auto_backup_cron_not_found"]="Cron не установлен. Устанавливаю..."
LANG_STRINGS["ru_auto_backup_cron_installed"]="Cron установлен и запущен."
LANG_STRINGS["ru_auto_backup_cron_install_failed"]="Не удалось установить cron. Пожалуйста, установите вручную."

LANG_STRINGS["en_auto_backup_hours_1"]="hour"
LANG_STRINGS["en_auto_backup_hours_2_4"]="hours"
LANG_STRINGS["en_auto_backup_hours_5_20"]="hours"
LANG_STRINGS["en_auto_backup_days_1"]="day"
LANG_STRINGS["en_auto_backup_days_2_4"]="days"
LANG_STRINGS["en_auto_backup_days_5_20"]="days"

LANG_STRINGS["ru_auto_backup_hours_1"]="час"
LANG_STRINGS["ru_auto_backup_hours_2_4"]="часа"
LANG_STRINGS["ru_auto_backup_hours_5_20"]="часов"
LANG_STRINGS["ru_auto_backup_days_1"]="день"
LANG_STRINGS["ru_auto_backup_days_2_4"]="дня"
LANG_STRINGS["ru_auto_backup_days_5_20"]="дней"

# backup
LANG_STRINGS["en_backup_enter_password"]="Enter archive password (minimum 8 characters):"
LANG_STRINGS["en_backup_password_short"]="Password must be at least 8 characters long"
LANG_STRINGS["en_backup_cmd_not_found"]="%s not found. Attempting to install..."
LANG_STRINGS["en_backup_install_failed"]="Failed to install %s. Please install manually."
LANG_STRINGS["en_backup_cmd_not_installed"]="%s is not installed. Please install manually."
LANG_STRINGS["en_backup_volume_not_found"]="Docker volume %s not found! No data to backup."
LANG_STRINGS["en_backup_dir_not_found"]="Directory %s not found! No data to backup."
LANG_STRINGS["en_backup_env_not_found"]="File .env not found in %s! No data to backup."
LANG_STRINGS["en_backup_compose_not_found"]="File docker-compose.yml not found in %s! No data to backup."
LANG_STRINGS["en_backup_volume"]="Creating backup of volume %s..."
LANG_STRINGS["en_backup_copying_configs"]="Copying configuration files..."
LANG_STRINGS["en_backup_creating_archive"]="Creating final archive with password..."
LANG_STRINGS["en_backup_archive_error"]="Error creating archive! Check 7z availability and write permissions."
LANG_STRINGS["en_backup_ready"]="Backup is ready: %s"
LANG_STRINGS["en_backup_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_backup_enter_password"]="Введите пароль для архива (минимум 8 символов):"
LANG_STRINGS["ru_backup_password_short"]="Пароль должен содержать минимум 8 символов"
LANG_STRINGS["ru_backup_cmd_not_found"]="%s не найден. Пытаемся установить..."
LANG_STRINGS["ru_backup_install_failed"]="Не удалось установить %s. Установите вручную."
LANG_STRINGS["ru_backup_cmd_not_installed"]="%s не установлен. Установите вручную."
LANG_STRINGS["ru_backup_volume_not_found"]="Docker volume %s не найден! Нет данных для резервной копии."
LANG_STRINGS["ru_backup_dir_not_found"]="Директория %s не найдена! Нет данных для резервной копии."
LANG_STRINGS["ru_backup_env_not_found"]="Файл .env не найден в %s! Нет данных для резервной копии."
LANG_STRINGS["ru_backup_compose_not_found"]="Файл docker-compose.yml не найден в %s! Нет данных для резервной копии."
LANG_STRINGS["ru_backup_volume"]="Создаём резервную копию тома %s..."
LANG_STRINGS["ru_backup_copying_configs"]="Копируем конфигурационные файлы..."
LANG_STRINGS["ru_backup_creating_archive"]="Создаём финальный архив с паролем..."
LANG_STRINGS["ru_backup_archive_error"]="Ошибка при создании архива! Проверьте наличие 7z и права на запись."
LANG_STRINGS["ru_backup_ready"]="Резервная копия готова: %s"
LANG_STRINGS["ru_backup_press_key"]="Нажмите любую клавишу для возврата в меню..."

# restore
LANG_STRINGS["en_restore_start"]="Starting Remnawave restore from backup"
LANG_STRINGS["en_restore_select_source"]="Select restore source (y - local, n - Telegram):"
LANG_STRINGS["en_restore_please_answer_yn"]="Please enter y or n to select source"
LANG_STRINGS["en_restore_enter_bot_token"]="Enter Telegram bot token:"
LANG_STRINGS["en_restore_enter_chat_id"]="Enter your Telegram chat_id:"
LANG_STRINGS["en_restore_send_backup"]="Send backup archive to bot or forward message with archive, then press any key to continue..."
LANG_STRINGS["en_restore_getting_backups"]="Getting list of available backups from Telegram..."
LANG_STRINGS["en_restore_no_backups"]="No backups found. Please try again."
LANG_STRINGS["en_restore_available_backups"]="Available backups in Telegram:"
LANG_STRINGS["en_restore_enter_backup_number"]="Enter backup number to restore:"
LANG_STRINGS["en_restore_invalid_choice"]="Invalid choice, please enter a valid number from the list."
LANG_STRINGS["en_restore_selected_backup"]="Selected backup: %s"
LANG_STRINGS["en_restore_downloading_archive"]="Downloading archive from Telegram..."
LANG_STRINGS["en_restore_download_failed"]="Failed to download archive from Telegram"
LANG_STRINGS["en_restore_no_local_backups"]="No archives found in %s. Place the required archive here and press any key to continue..."
LANG_STRINGS["en_restore_press_key_continue"]="Press any key to continue..."
LANG_STRINGS["en_restore_no_backups_found"]="No backup archives found. Place file in %s or press 'n' to cancel restore."
LANG_STRINGS["en_restore_exit"]="Exiting restore."
LANG_STRINGS["en_restore_available_local_backups"]="Available local backups:"
LANG_STRINGS["en_restore_enter_password"]="Enter archive password (minimum 8 characters):"
LANG_STRINGS["en_restore_password_short"]="Password too short. Enter password at least 8 characters long."
LANG_STRINGS["en_restore_7z_not_found"]="7zip not found. Installing..."
LANG_STRINGS["en_restore_docker_not_found"]="Docker not found. Attempting to install..."
LANG_STRINGS["en_restore_creating_directory"]="Creating Remnawave directory: %s"
LANG_STRINGS["en_restore_checking_archive"]="Checking archive..."
LANG_STRINGS["en_restore_invalid_password"]="Invalid password or corrupted archive. Check entered data and try again."
LANG_STRINGS["en_restore_backup_before"]="Creating backup of current data before restore..."
LANG_STRINGS["en_restore_backup_saved"]="Current data backup saved: %s"
LANG_STRINGS["en_restore_stopping_containers"]="Stopping and removing current containers..."
LANG_STRINGS["en_restore_removing_old_data"]="Removing old volumes and files..."
LANG_STRINGS["en_restore_restoring_configs"]="Restoring configuration files from archive..."
LANG_STRINGS["en_restore_starting_containers"]="Starting containers for database initialization..."
LANG_STRINGS["en_restore_stopping_containers_again"]="Stopping containers..."
LANG_STRINGS["en_restore_clearing_database"]="Clearing database contents..."
LANG_STRINGS["en_restore_restoring_database"]="Restoring database from backup..."
LANG_STRINGS["en_restore_removing_temp"]="Removing temporary files..."
LANG_STRINGS["en_restore_starting_remnawave"]="Starting Remnawave containers..."
LANG_STRINGS["en_restore_complete"]="Restore completed successfully!"
LANG_STRINGS["en_restore_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_restore_start"]="Начинаем восстановление Remnawave из резервной копии"
LANG_STRINGS["ru_restore_select_source"]="Выберите источник восстановления (y - локальный, n - Telegram):"
LANG_STRINGS["ru_restore_please_answer_yn"]="Пожалуйста, введите y или n для выбора источника"
LANG_STRINGS["ru_restore_enter_bot_token"]="Введите токен Telegram-бота:"
LANG_STRINGS["ru_restore_enter_chat_id"]="Введите ваш chat_id в Telegram:"
LANG_STRINGS["ru_restore_send_backup"]="Отправьте архив резервной копии боту или перешлите сообщение с архивом, затем нажмите любую клавишу для продолжения..."
LANG_STRINGS["ru_restore_getting_backups"]="Получаем список доступных резервных копий из Telegram..."
LANG_STRINGS["ru_restore_no_backups"]="Резервные копии не найдены. Пожалуйста, повторите попытку."
LANG_STRINGS["ru_restore_available_backups"]="Доступные резервные копии в Telegram:"
LANG_STRINGS["ru_restore_enter_backup_number"]="Введите номер архива для восстановления:"
LANG_STRINGS["ru_restore_invalid_choice"]="Неверный выбор, пожалуйста, введите корректный номер из списка."
LANG_STRINGS["ru_restore_selected_backup"]="Выбран архив: %s"
LANG_STRINGS["ru_restore_downloading_archive"]="Загружаем архив из Telegram..."
LANG_STRINGS["ru_restore_download_failed"]="Не удалось скачать архив из Telegram"
LANG_STRINGS["ru_restore_no_local_backups"]="В папке %s не найдено архивов. Поместите сюда нужный архив и нажмите любую клавишу для продолжения..."
LANG_STRINGS["ru_restore_press_key_continue"]="Нажмите любую клавишу для продолжения..."
LANG_STRINGS["ru_restore_no_backups_found"]="Архивы резервных копий не обнаружены. Положите файл в папку %s или нажмите 'n' для отмены восстановления."
LANG_STRINGS["ru_restore_exit"]="Выход из восстановления."
LANG_STRINGS["ru_restore_available_local_backups"]="Доступные локальные резервные копии:"
LANG_STRINGS["ru_restore_enter_password"]="Введите пароль от архива (минимум 8 символов):"
LANG_STRINGS["ru_restore_password_short"]="Пароль слишком короткий. Введите пароль длиной не менее 8 символов."
LANG_STRINGS["ru_restore_7z_not_found"]="7zip не найден. Устанавливаю..."
LANG_STRINGS["ru_restore_docker_not_found"]="Docker не найден. Пытаемся установить..."
LANG_STRINGS["ru_restore_creating_directory"]="Создаём директорию Remnawave: %s"
LANG_STRINGS["ru_restore_checking_archive"]="Проверяем архив..."
LANG_STRINGS["ru_restore_invalid_password"]="Неверный пароль или повреждённый архив. Проверьте правильность введённых данных и попробуйте снова."
LANG_STRINGS["ru_restore_backup_before"]="Создаём резервную копию текущих данных перед восстановлением..."
LANG_STRINGS["ru_restore_backup_saved"]="Резервная копия текущих данных сохранена: %s"
LANG_STRINGS["ru_restore_stopping_containers"]="Останавливаем и удаляем текущие контейнеры..."
LANG_STRINGS["ru_restore_removing_old_data"]="Удаляем старые тома и файлы..."
LANG_STRINGS["ru_restore_restoring_configs"]="Восстанавливаем конфигурационные файлы из архива..."
LANG_STRINGS["ru_restore_starting_containers"]="Запускаем контейнеры для инициализации базы данных..."
LANG_STRINGS["ru_restore_stopping_containers_again"]="Останавливаем контейнеры..."
LANG_STRINGS["ru_restore_clearing_database"]="Очищаем содержимое базы данных..."
LANG_STRINGS["ru_restore_restoring_database"]="Восстанавливаем базу данных из резервной копии..."
LANG_STRINGS["ru_restore_removing_temp"]="Удаляем временные файлы..."
LANG_STRINGS["ru_restore_starting_remnawave"]="Запускаем контейнеры Remnawave..."
LANG_STRINGS["ru_restore_complete"]="Восстановление завершено успешно!"
LANG_STRINGS["ru_restore_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnanode
# Remnanode-install-bbr
LANG_STRINGS["en_install_bbr_already_configured"]="BBR is already configured"
LANG_STRINGS["en_install_bbr_installing"]="Installing BBR..."
LANG_STRINGS["en_install_bbr_installed"]="BBR successfully installed!"
LANG_STRINGS["en_install_bbr_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_bbr_already_configured"]="BBR уже настроен"
LANG_STRINGS["ru_install_bbr_installing"]="Установка BBR..."
LANG_STRINGS["ru_install_bbr_installed"]="BBR успешно установлен!"
LANG_STRINGS["ru_install_bbr_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnanode-install-caddy
LANG_STRINGS["en_install_caddy_node_already_installed"]="Caddy is already installed"
LANG_STRINGS["en_install_caddy_node_update_config"]="Do you want to update Caddy configuration? (y/n):"
LANG_STRINGS["en_install_caddy_node_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_caddy_node_installing"]="Installing Caddy..."
LANG_STRINGS["en_install_caddy_node_installed"]="Caddy successfully installed!"
LANG_STRINGS["en_install_caddy_node_setup_site"]="Setting up camouflage site..."
LANG_STRINGS["en_install_caddy_node_site_configured"]="Camouflage site configured!"
LANG_STRINGS["en_install_caddy_node_updating_config"]="Updating Caddy configuration..."
LANG_STRINGS["en_install_caddy_node_config_updated"]="Caddy configuration updated!"
LANG_STRINGS["en_install_caddy_node_enter_domain"]="Enter domain for self-steal (e.g., noda1.domain.com):"
LANG_STRINGS["en_install_caddy_node_domain_empty"]="Domain cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_node_enter_port"]="Enter port for self-steal (default 8443):"
LANG_STRINGS["en_install_caddy_node_port_must_be_number"]="Port must be a number."
LANG_STRINGS["en_install_caddy_node_installation_complete"]="Installation completed!"
LANG_STRINGS["en_install_caddy_node_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_caddy_node_already_installed"]="Caddy уже установлен"
LANG_STRINGS["ru_install_caddy_node_update_config"]="Хотите скорректировать конфигурацию Caddy? (y/n):"
LANG_STRINGS["ru_install_caddy_node_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_caddy_node_installing"]="Установка Caddy..."
LANG_STRINGS["ru_install_caddy_node_installed"]="Caddy успешно установлен!"
LANG_STRINGS["ru_install_caddy_node_setup_site"]="Настройка сайта маскировки..."
LANG_STRINGS["ru_install_caddy_node_site_configured"]="Сайт маскировки настроен!"
LANG_STRINGS["ru_install_caddy_node_updating_config"]="Обновление конфигурации Caddy..."
LANG_STRINGS["ru_install_caddy_node_config_updated"]="Конфигурация Caddy обновлена!"
LANG_STRINGS["ru_install_caddy_node_enter_domain"]="Введите доменное для self-steal (например, noda1.domain.com):"
LANG_STRINGS["ru_install_caddy_node_domain_empty"]="Домен не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_node_enter_port"]="Введите порт для self-steal (по умолчанию 8443):"
LANG_STRINGS["ru_install_caddy_node_port_must_be_number"]="Порт должен быть числом."
LANG_STRINGS["ru_install_caddy_node_installation_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_caddy_node_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnanode-install-full
LANG_STRINGS["en_install_full_node_start"]="Starting full Remnanode installation..."
LANG_STRINGS["en_install_full_node_checking_components"]="Checking installed components..."
LANG_STRINGS["en_install_full_node_docker_installed"]="Docker is already installed"
LANG_STRINGS["en_install_full_node_docker_not_installed"]="Docker is not installed"
LANG_STRINGS["en_install_full_node_remnanode_installed"]="Remnanode is already installed"
LANG_STRINGS["en_install_full_node_update_remnanode"]="Do you want to update Remnanode settings? (y/n):"
LANG_STRINGS["en_install_full_node_caddy_installed"]="Caddy is already installed"
LANG_STRINGS["en_install_full_node_update_caddy"]="Do you want to update Caddy settings? (y/n):"
LANG_STRINGS["en_install_full_node_tblocker_installed"]="Tblocker is already installed"
LANG_STRINGS["en_install_full_node_update_tblocker"]="Do you want to update Tblocker settings? (y/n):"
LANG_STRINGS["en_install_full_node_warp_installed"]="WARP is already installed"
LANG_STRINGS["en_install_full_node_update_warp"]="Do you want to update WARP settings? (y/n):"
LANG_STRINGS["en_install_full_node_warp_skip"]="WARP settings will not be updated"
LANG_STRINGS["en_install_full_node_bbr_configured"]="BBR is already configured, skipping installation"
LANG_STRINGS["en_install_full_node_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_full_node_enter_domain"]="Enter domain for self-steal (e.g., noda1.domain.com, n to skip):"
LANG_STRINGS["en_install_full_node_confirm_skip_caddy"]="Are you sure you want to skip Caddy installation? (y/n):"
LANG_STRINGS["en_install_full_node_domain_empty"]="Domain cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_node_enter_port"]="Enter port for self-steal (default 8443, n to skip):"
LANG_STRINGS["en_install_full_node_port_must_be_number"]="Port must be a number."
LANG_STRINGS["en_install_full_node_enter_app_port"]="Enter APP_PORT (default 3001, n to skip):"
LANG_STRINGS["en_install_full_node_confirm_skip_remnanode"]="Are you sure you want to skip Remnanode installation? (y/n):"
LANG_STRINGS["en_install_full_node_enter_ssl_cert"]="Enter SSL_CERT (can be obtained when adding node to panel, n to skip):"
LANG_STRINGS["en_install_full_node_ssl_cert_empty"]="SSL_CERT cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_node_enter_bot_token"]="Enter bot token for Tblocker (create bot in @BotFather for notifications, n to skip):"
LANG_STRINGS["en_install_full_node_confirm_skip_tblocker"]="Are you sure you want to skip Tblocker installation? (y/n):"
LANG_STRINGS["en_install_full_node_bot_token_empty"]="Bot token cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_node_enter_chat_id"]="Enter Telegram ID admin for Tblocker (n to skip):"
LANG_STRINGS["en_install_full_node_chat_id_empty"]="Telegram ID admin cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_node_enter_block_duration"]="Enter user block duration (in minutes, default 10):"
LANG_STRINGS["en_install_full_node_need_webhook"]="Do you need webhook configuration? (y/n):"
LANG_STRINGS["en_install_full_node_enter_webhook"]="Enter webhook address (example portal.domain.com/tblocker/webhook):"
LANG_STRINGS["en_install_full_node_webhook_empty"]="Webhook address cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_node_enter_warp_port"]="Enter port for WARP (1000-65535, default 40000, n to skip):"
LANG_STRINGS["en_install_full_node_confirm_skip_warp"]="Are you sure you want to skip WARP installation? (y/n):"
LANG_STRINGS["en_install_full_node_warp_port_range"]="Port must be a number between 1000 and 65535."
LANG_STRINGS["en_install_full_node_need_bbr"]="Do you need BBR installation? (y/n):"
LANG_STRINGS["en_install_full_node_updating_packages"]="Updating system packages..."
LANG_STRINGS["en_install_full_node_installing_docker"]="Installing Docker..."
LANG_STRINGS["en_install_full_node_docker_error"]="Error: Failed to install Docker."
LANG_STRINGS["en_install_full_node_docker_installed_success"]="Docker successfully installed!"
LANG_STRINGS["en_install_full_node_installing_warp"]="Installing WARP (WireProxy)..."
LANG_STRINGS["en_install_full_node_installing_expect"]="Installing expect package for WARP installation automation..."
LANG_STRINGS["en_install_full_node_warp_installed_success"]="WARP successfully installed!"
LANG_STRINGS["en_install_full_node_installing_bbr"]="Configuring TCP BBR..."
LANG_STRINGS["en_install_full_node_bbr_installed_success"]="BBR successfully configured!"
LANG_STRINGS["en_install_full_node_installing_caddy"]="Installing Caddy..."
LANG_STRINGS["en_install_full_node_setup_site"]="Setting up camouflage site..."
LANG_STRINGS["en_install_full_node_updating_caddy_config"]="Updating Caddy configuration..."
LANG_STRINGS["en_install_full_node_caddy_installed_success"]="Caddy successfully installed!"
LANG_STRINGS["en_install_full_node_installing_remnanode"]="Installing Remnanode..."
LANG_STRINGS["en_install_full_node_tblocker_integration"]="Tblocker is already installed, using docker-compose with integration"
LANG_STRINGS["en_install_full_node_tblocker_data_provided"]="Tblocker data provided, using docker-compose with integration"
LANG_STRINGS["en_install_full_node_using_standard_compose"]="Using standard docker-compose"
LANG_STRINGS["en_install_full_node_remnanode_error"]="Error: Failed to start Remnanode. Make sure Docker is configured correctly."
LANG_STRINGS["en_install_full_node_remnanode_installed_success"]="Remnanode successfully installed!"
LANG_STRINGS["en_install_full_node_installing_tblocker"]="Installing Tblocker..."
LANG_STRINGS["en_install_full_node_tblocker_download_error"]="Error: Failed to download Tblocker script."
LANG_STRINGS["en_install_full_node_tblocker_script_error"]="Error: Failed to execute Tblocker script."
LANG_STRINGS["en_install_full_node_tblocker_config_error"]="Error: File /opt/tblocker/config.yaml not found."
LANG_STRINGS["en_install_full_node_setup_crontab"]="Setting up crontab..."
LANG_STRINGS["en_install_full_node_tblocker_installed_success"]="Tblocker successfully installed!"
LANG_STRINGS["en_install_full_node_complete"]="Installation completed!"
LANG_STRINGS["en_install_full_node_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_full_node_start"]="Начало полной установки Remnanode..."
LANG_STRINGS["ru_install_full_node_checking_components"]="Проверка установленных компонентов..."
LANG_STRINGS["ru_install_full_node_docker_installed"]="Docker уже установлен"
LANG_STRINGS["ru_install_full_node_docker_not_installed"]="Docker не установлен"
LANG_STRINGS["ru_install_full_node_remnanode_installed"]="Remnanode уже установлен"
LANG_STRINGS["ru_install_full_node_update_remnanode"]="Хотите скорректировать настройки Remnanode? (y/n):"
LANG_STRINGS["ru_install_full_node_caddy_installed"]="Caddy уже установлен"
LANG_STRINGS["ru_install_full_node_update_caddy"]="Хотите скорректировать настройки Caddy? (y/n):"
LANG_STRINGS["ru_install_full_node_tblocker_installed"]="Tblocker уже установлен"
LANG_STRINGS["ru_install_full_node_update_tblocker"]="Хотите скорректировать настройки Tblocker? (y/n):"
LANG_STRINGS["ru_install_full_node_warp_installed"]="WARP уже установлен"
LANG_STRINGS["ru_install_full_node_update_warp"]="Хотите скорректировать настройки WARP? (y/n):"
LANG_STRINGS["ru_install_full_node_warp_skip"]="Настройки WARP не будут обновлены"
LANG_STRINGS["ru_install_full_node_bbr_configured"]="BBR уже настроен, пропускаем установку"
LANG_STRINGS["ru_install_full_node_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_full_node_enter_domain"]="Введите доменное имя для self-steal (например, noda1.domain.com, n для пропуска):"
LANG_STRINGS["ru_install_full_node_confirm_skip_caddy"]="Вы точно хотите пропустить установку Caddy? (y/n):"
LANG_STRINGS["ru_install_full_node_domain_empty"]="Доменное имя не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_node_enter_port"]="Введите порт для self-steal (по умолчанию 8443, n для пропуска):"
LANG_STRINGS["ru_install_full_node_port_must_be_number"]="Порт должен быть числом."
LANG_STRINGS["ru_install_full_node_enter_app_port"]="Введите APP_PORT (по умолчанию 3001, n для пропуска):"
LANG_STRINGS["ru_install_full_node_confirm_skip_remnanode"]="Вы точно хотите пропустить установку Remnanode? (y/n):"
LANG_STRINGS["ru_install_full_node_enter_ssl_cert"]="Введите SSL_CERT (можно получить при добавлении ноды в панели, n для пропуска):"
LANG_STRINGS["ru_install_full_node_ssl_cert_empty"]="SSL_CERT не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_node_enter_bot_token"]="Введите токен бота для Tblocker (создайте бота в @BotFather для оповещений, n для пропуска):"
LANG_STRINGS["ru_install_full_node_confirm_skip_tblocker"]="Вы точно хотите пропустить установку Tblocker? (y/n):"
LANG_STRINGS["ru_install_full_node_bot_token_empty"]="Токен бота не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_node_enter_chat_id"]="Введите Telegram ID админа для Tblocker (n для пропуска):"
LANG_STRINGS["ru_install_full_node_chat_id_empty"]="Telegram ID админа не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_node_enter_block_duration"]="Укажите время блокировки пользователя (указывается значение в минутах, по умолчанию 10):"
LANG_STRINGS["ru_install_full_node_need_webhook"]="Требуется настройка отправки вебхуков? (y/n):"
LANG_STRINGS["ru_install_full_node_enter_webhook"]="Укажите адрес вебхука (пример portal.domain.com/tblocker/webhook):"
LANG_STRINGS["ru_install_full_node_webhook_empty"]="Адрес вебхука не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_node_enter_warp_port"]="Введите порт для WARP (1000-65535, по умолчанию 40000, n для пропуска):"
LANG_STRINGS["ru_install_full_node_confirm_skip_warp"]="Вы точно хотите пропустить установку WARP? (y/n):"
LANG_STRINGS["ru_install_full_node_warp_port_range"]="Порт должен быть числом от 1000 до 65535."
LANG_STRINGS["ru_install_full_node_need_bbr"]="Требуется установка BBR? (y/n):"
LANG_STRINGS["ru_install_full_node_updating_packages"]="Обновление пакетов системы..."
LANG_STRINGS["ru_install_full_node_installing_docker"]="Установка Docker..."
LANG_STRINGS["ru_install_full_node_docker_error"]="Ошибка: Не удалось установить Docker."
LANG_STRINGS["ru_install_full_node_docker_installed_success"]="Docker успешно установлен!"
LANG_STRINGS["ru_install_full_node_installing_warp"]="Установка WARP (WireProxy)..."
LANG_STRINGS["ru_install_full_node_installing_expect"]="Устанавливается пакет expect для автоматизации установки WARP..."
LANG_STRINGS["ru_install_full_node_warp_installed_success"]="WARP успешно установлен!"
LANG_STRINGS["ru_install_full_node_installing_bbr"]="Настройка TCP BBR..."
LANG_STRINGS["ru_install_full_node_bbr_installed_success"]="BBR успешно настроен!"
LANG_STRINGS["ru_install_full_node_installing_caddy"]="Установка Caddy..."
LANG_STRINGS["ru_install_full_node_setup_site"]="Настройка сайта маскировки..."
LANG_STRINGS["ru_install_full_node_updating_caddy_config"]="Обновление конфигурации Caddy..."
LANG_STRINGS["ru_install_full_node_caddy_installed_success"]="Caddy успешно установлен!"
LANG_STRINGS["ru_install_full_node_installing_remnanode"]="Установка Remnanode..."
LANG_STRINGS["ru_install_full_node_tblocker_integration"]="Tblocker уже установлен, используем docker-compose с интеграцией"
LANG_STRINGS["ru_install_full_node_tblocker_data_provided"]="Данные Tblocker предоставлены, используем docker-compose с интеграцией"
LANG_STRINGS["ru_install_full_node_using_standard_compose"]="Используем стандартный docker-compose"
LANG_STRINGS["ru_install_full_node_remnanode_error"]="Ошибка: Не удалось запустить Remnanode. Убедитесь, что Docker настроен корректно."
LANG_STRINGS["ru_install_full_node_remnanode_installed_success"]="Remnanode успешно установлен!"
LANG_STRINGS["ru_install_full_node_installing_tblocker"]="Установка Tblocker..."
LANG_STRINGS["ru_install_full_node_tblocker_download_error"]="Ошибка: Не удалось скачать скрипт Tblocker."
LANG_STRINGS["ru_install_full_node_tblocker_script_error"]="Ошибка: Не удалось выполнить скрипт Tblocker."
LANG_STRINGS["ru_install_full_node_tblocker_config_error"]="Ошибка: Файл /opt/tblocker/config.yaml не найден."
LANG_STRINGS["ru_install_full_node_setup_crontab"]="Настройка crontab..."
LANG_STRINGS["ru_install_full_node_tblocker_installed_success"]="Tblocker успешно установлен!"
LANG_STRINGS["ru_install_full_node_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_full_node_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnanode-install-node
LANG_STRINGS["en_install_node_docker_installed"]="Docker is already installed, skipping installation."
LANG_STRINGS["en_install_node_installing_docker"]="Installing Docker..."
LANG_STRINGS["en_install_node_docker_error"]="Error: Failed to install Docker."
LANG_STRINGS["en_install_node_docker_success"]="Docker successfully installed!"
LANG_STRINGS["en_install_node_already_installed"]="Remnanode is already installed"
LANG_STRINGS["en_install_node_update_settings"]="Do you want to adjust Remnanode settings? (y/n):"
LANG_STRINGS["en_install_node_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_node_installing"]="Installing Remnanode..."
LANG_STRINGS["en_install_node_error"]="Error: Failed to start Remnanode. Make sure Docker is configured correctly."
LANG_STRINGS["en_install_node_success"]="Remnanode successfully installed!"
LANG_STRINGS["en_install_node_enter_app_port"]="Enter APP_PORT (default 3001):"
LANG_STRINGS["en_install_node_port_must_be_number"]="Port must be a number."
LANG_STRINGS["en_install_node_enter_ssl_cert"]="Enter SSL_CERT (can be obtained when adding node to panel):"
LANG_STRINGS["en_install_node_ssl_cert_empty"]="SSL_CERT cannot be empty. Please enter a value."
LANG_STRINGS["en_install_node_use_tblocker"]="Will Tblocker be used? (y/n):"
LANG_STRINGS["en_install_node_complete"]="Installation completed!"
LANG_STRINGS["en_install_node_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_node_docker_installed"]="Docker уже установлен, пропускаем установку."
LANG_STRINGS["ru_install_node_installing_docker"]="Установка Docker..."
LANG_STRINGS["ru_install_node_docker_error"]="Ошибка: Не удалось установить Docker."
LANG_STRINGS["ru_install_node_docker_success"]="Docker успешно установлен!"
LANG_STRINGS["ru_install_node_already_installed"]="Remnanode уже установлен"
LANG_STRINGS["ru_install_node_update_settings"]="Хотите скорректировать настройки Remnanode? (y/n):"
LANG_STRINGS["ru_install_node_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_node_installing"]="Установка Remnanode..."
LANG_STRINGS["ru_install_node_error"]="Ошибка: Не удалось запустить Remnanode. Убедитесь, что Docker настроен корректно."
LANG_STRINGS["ru_install_node_success"]="Remnanode успешно установлен!"
LANG_STRINGS["ru_install_node_enter_app_port"]="Введите APP_PORT (по умолчанию 3001):"
LANG_STRINGS["ru_install_node_port_must_be_number"]="Порт должен быть числом."
LANG_STRINGS["ru_install_node_enter_ssl_cert"]="Введите SSL_CERT (можно получить при добавлении ноды в панели):"
LANG_STRINGS["ru_install_node_ssl_cert_empty"]="SSL_CERT не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_node_use_tblocker"]="Будет ли использоваться Tblocker? (y/n):"
LANG_STRINGS["ru_install_node_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_node_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnanode-install-tblocker
LANG_STRINGS["en_install_tblocker_remnanode_installed"]="Remnanode is installed"
LANG_STRINGS["en_install_tblocker_update_docker"]="Do you want to update docker-compose file for Tblocker integration? (y/n):"
LANG_STRINGS["en_install_tblocker_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_tblocker_update_compose"]="Updating docker-compose file..."
LANG_STRINGS["en_install_tblocker_compose_updated"]="Docker-compose file updated!"
LANG_STRINGS["en_install_tblocker_already_installed"]="Tblocker is already installed"
LANG_STRINGS["en_install_tblocker_update_config"]="Do you want to update configuration? (y/n):"
LANG_STRINGS["en_install_tblocker_press_key"]="Press any key to return to menu..."
LANG_STRINGS["en_install_tblocker_need_webhook"]="Do you need webhook configuration? (y/n):"
LANG_STRINGS["en_install_tblocker_enter_webhook"]="Enter webhook address (example portal.domain.com/tblocker/webhook):"
LANG_STRINGS["en_install_tblocker_webhook_empty"]="Webhook address cannot be empty. Please enter a value."
LANG_STRINGS["en_install_tblocker_setup_crontab"]="Setting up crontab..."
LANG_STRINGS["en_install_tblocker_crontab_configured"]="Crontab configured!"
LANG_STRINGS["en_install_tblocker_installing"]="Installing Tblocker..."
LANG_STRINGS["en_install_tblocker_download_error"]="Error: Failed to download Tblocker script."
LANG_STRINGS["en_install_tblocker_script_error"]="Error: Failed to execute Tblocker script."
LANG_STRINGS["en_install_tblocker_config_error"]="Error: File /opt/tblocker/config.yaml not found."
LANG_STRINGS["en_install_tblocker_installed_success"]="Tblocker successfully installed!"
LANG_STRINGS["en_install_tblocker_updating_config"]="Updating Tblocker configuration..."
LANG_STRINGS["en_install_tblocker_config_updated"]="Tblocker configuration updated!"
LANG_STRINGS["en_install_tblocker_enter_bot_token"]="Enter bot token for Tblocker (create bot in @BotFather for notifications):"
LANG_STRINGS["en_install_tblocker_bot_token_empty"]="Bot token cannot be empty. Please enter a value."
LANG_STRINGS["en_install_tblocker_enter_chat_id"]="Enter Telegram ID admin for Tblocker:"
LANG_STRINGS["en_install_tblocker_chat_id_empty"]="Telegram ID admin cannot be empty. Please enter a value."
LANG_STRINGS["en_install_tblocker_enter_block_duration"]="Enter user block duration (in minutes, default 10):"
LANG_STRINGS["en_install_tblocker_complete"]="Installation completed!"
LANG_STRINGS["en_install_tblocker_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_tblocker_remnanode_installed"]="Remnanode установлен"
LANG_STRINGS["ru_install_tblocker_update_docker"]="Хотите обновить docker-compose файл для интеграции с Tblocker? (y/n):"
LANG_STRINGS["ru_install_tblocker_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_tblocker_update_compose"]="Обновление docker-compose файла..."
LANG_STRINGS["ru_install_tblocker_compose_updated"]="Docker-compose файл обновлен!"
LANG_STRINGS["ru_install_tblocker_already_installed"]="Tblocker уже установлен"
LANG_STRINGS["ru_install_tblocker_update_config"]="Желаете обновить конфигурацию? (y/n):"
LANG_STRINGS["ru_install_tblocker_press_key"]="Нажмите любую клавишу для возврата в меню..."
LANG_STRINGS["ru_install_tblocker_need_webhook"]="Требуется настройка отправки вебхуков? (y/n):"
LANG_STRINGS["ru_install_tblocker_enter_webhook"]="Укажите адрес вебхука (пример portal.domain.com/tblocker/webhook):"
LANG_STRINGS["ru_install_tblocker_webhook_empty"]="Адрес вебхука не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_tblocker_setup_crontab"]="Настройка crontab..."
LANG_STRINGS["ru_install_tblocker_crontab_configured"]="Crontab настроен!"
LANG_STRINGS["ru_install_tblocker_installing"]="Установка Tblocker..."
LANG_STRINGS["ru_install_tblocker_download_error"]="Ошибка: Не удалось скачать скрипт Tblocker."
LANG_STRINGS["ru_install_tblocker_script_error"]="Ошибка: Не удалось выполнить скрипт Tblocker."
LANG_STRINGS["ru_install_tblocker_config_error"]="Ошибка: Файл /opt/tblocker/config.yaml не найден."
LANG_STRINGS["ru_install_tblocker_installed_success"]="Tblocker успешно установлен!"
LANG_STRINGS["ru_install_tblocker_updating_config"]="Обновление конфигурации Tblocker..."
LANG_STRINGS["ru_install_tblocker_config_updated"]="Конфигурация Tblocker обновлена!"
LANG_STRINGS["ru_install_tblocker_enter_bot_token"]="Введите токен бота для Tblocker (создайте бота в @BotFather для оповещений):"
LANG_STRINGS["ru_install_tblocker_bot_token_empty"]="Токен бота не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_tblocker_enter_chat_id"]="Введите Telegram ID админа для Tblocker:"
LANG_STRINGS["ru_install_tblocker_chat_id_empty"]="Telegram ID админа не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_tblocker_enter_block_duration"]="Укажите время блокировки пользователя (указывается значение в минутах, по умолчанию 10):"
LANG_STRINGS["ru_install_tblocker_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_tblocker_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnanode-install-warp
LANG_STRINGS["en_install_warp_already_installed"]="WARP is already installed"
LANG_STRINGS["en_install_warp_reconfigure"]="Do you want to reconfigure WARP? (y/n):"
LANG_STRINGS["en_install_warp_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_warp_press_key"]="Press any key to return to menu..."
LANG_STRINGS["en_install_warp_installing"]="Installing WARP (WireProxy)..."
LANG_STRINGS["en_install_warp_installing_expect"]="Installing expect package for WARP installation automation..."
LANG_STRINGS["en_install_warp_installed_success"]="WARP successfully installed!"
LANG_STRINGS["en_install_warp_enter_port"]="Enter port for WARP (1000-65535, default 40000):"
LANG_STRINGS["en_install_warp_port_range"]="Port must be a number between 1000 and 65535."

LANG_STRINGS["ru_install_warp_already_installed"]="WARP уже установлен"
LANG_STRINGS["ru_install_warp_reconfigure"]="Хотите перенастроить WARP? (y/n):"
LANG_STRINGS["ru_install_warp_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_warp_press_key"]="Нажмите любую клавишу для возврата в меню..."
LANG_STRINGS["ru_install_warp_installing"]="Установка WARP (WireProxy)..."
LANG_STRINGS["ru_install_warp_installing_expect"]="Устанавливается пакет expect для автоматизации установки WARP..."
LANG_STRINGS["ru_install_warp_installed_success"]="WARP успешно установлен!"
LANG_STRINGS["ru_install_warp_enter_port"]="Введите порт для WARP (1000-65535, по умолчанию 40000):"
LANG_STRINGS["ru_install_warp_port_range"]="Порт должен быть числом от 1000 до 65535."

# Remnanode-update-node
LANG_STRINGS["en_update_node_updating"]="Updating Remnanode node..."
LANG_STRINGS["en_update_node_complete"]="Update completed!"
LANG_STRINGS["en_update_node_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_update_node_updating"]="Обновление ноды Remnanode..."
LANG_STRINGS["ru_update_node_complete"]="Обновление завершено!"
LANG_STRINGS["ru_update_node_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnawave
# Remnawave-install-caddy
LANG_STRINGS["en_install_caddy_detected"]="Caddy installation detected"
LANG_STRINGS["en_install_caddy_reinstall"]="Reinstall Caddy? (y/n):"
LANG_STRINGS["en_install_caddy_stopping"]="Stopping and removing existing installation..."
LANG_STRINGS["en_install_caddy_reinstall_denied"]="Caddy reinstallation denied"
LANG_STRINGS["en_install_caddy_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_caddy_installing"]="Installing Caddy..."
LANG_STRINGS["en_install_caddy_need_protection"]="Do you need panel protection with custom path (Without protection /api/* and /api/sub/*)? (y/n):"
LANG_STRINGS["en_install_caddy_enter_panel_domain"]="Enter panel domain (e.g., panel.domain.com):"
LANG_STRINGS["en_install_caddy_domain_empty"]="Panel domain cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_enter_sub_domain"]="Enter subscription domain (e.g., sub.domain.com):"
LANG_STRINGS["en_install_caddy_enter_panel_port"]="Enter panel port (default 3000):"
LANG_STRINGS["en_install_caddy_enter_sub_port"]="Enter subscription port (default 3010):"
LANG_STRINGS["en_install_caddy_enter_project_name"]="Enter project name:"
LANG_STRINGS["en_install_caddy_project_name_empty"]="Project name cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_enter_project_description"]="Enter subscription page description:"
LANG_STRINGS["en_install_caddy_project_description_empty"]="Project description cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_enter_login_route"]="Enter panel access path (e.g., supersecretroute):"
LANG_STRINGS["en_install_caddy_login_route_empty"]="Panel access path cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_enter_admin_login"]="Enter administrator login:"
LANG_STRINGS["en_install_caddy_admin_login_empty"]="Administrator login cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_enter_admin_email"]="Enter administrator email:"
LANG_STRINGS["en_install_caddy_admin_email_empty"]="Administrator email cannot be empty. Please enter a value."
LANG_STRINGS["en_install_caddy_enter_admin_password"]="Enter administrator password (min. 8 characters, at least one uppercase, lowercase, number and special character):"
LANG_STRINGS["en_install_caddy_password_short"]="Password too short! Minimum 8 characters."
LANG_STRINGS["en_install_caddy_password_uppercase"]="Password must contain at least one uppercase letter (A-Z)."
LANG_STRINGS["en_install_caddy_password_lowercase"]="Password must contain at least one lowercase letter (a-z)."
LANG_STRINGS["en_install_caddy_password_number"]="Password must contain at least one number (0-9)."
LANG_STRINGS["en_install_caddy_password_special"]="Password must contain at least one special character (!, @, #, $, %, ^, &, *, -, +, =, ? etc.)."
LANG_STRINGS["en_install_caddy_complete"]="Installation completed!"
LANG_STRINGS["en_install_caddy_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_caddy_detected"]="Обнаружена установка Caddy"
LANG_STRINGS["ru_install_caddy_reinstall"]="Переустановить Caddy? (y/n):"
LANG_STRINGS["ru_install_caddy_stopping"]="Останавливаем и удаляем существующую установку..."
LANG_STRINGS["ru_install_caddy_reinstall_denied"]="Отказано в переустановке Caddy"
LANG_STRINGS["ru_install_caddy_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_caddy_installing"]="Установка Caddy..."
LANG_STRINGS["ru_install_caddy_need_protection"]="Требуется ли защита панели кастомным путем (Без защиты /api/* и /api/sub/*)? (y/n):"
LANG_STRINGS["ru_install_caddy_enter_panel_domain"]="Введите домен панели (например, panel.domain.com):"
LANG_STRINGS["ru_install_caddy_domain_empty"]="Домен панели не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_enter_sub_domain"]="Введите домен подписок (например, sub.domain.com):"
LANG_STRINGS["ru_install_caddy_enter_panel_port"]="Введите порт панели (по умолчанию 3000):"
LANG_STRINGS["ru_install_caddy_enter_sub_port"]="Введите порт подписок (по умолчанию 3010):"
LANG_STRINGS["ru_install_caddy_enter_project_name"]="Введите имя проекта:"
LANG_STRINGS["ru_install_caddy_project_name_empty"]="Имя проекта не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_enter_project_description"]="Введите описание страницы подписки:"
LANG_STRINGS["ru_install_caddy_project_description_empty"]="Описание проекта не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_enter_login_route"]="Введите путь доступа к панели (например, supersecretroute):"
LANG_STRINGS["ru_install_caddy_login_route_empty"]="Путь доступа к панели не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_enter_admin_login"]="Введите логин администратора:"
LANG_STRINGS["ru_install_caddy_admin_login_empty"]="Логин администратора не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_enter_admin_email"]="Введите email администратора:"
LANG_STRINGS["ru_install_caddy_admin_email_empty"]="Email администратора не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_caddy_enter_admin_password"]="Введите пароль администратора (мин. 8 символов, хотя бы одна заглавная, строчная, цифра и спецсимвол):"
LANG_STRINGS["ru_install_caddy_password_short"]="Пароль слишком короткий! Минимум 8 символов."
LANG_STRINGS["ru_install_caddy_password_uppercase"]="Пароль должен содержать хотя бы одну заглавную букву (A-Z)."
LANG_STRINGS["ru_install_caddy_password_lowercase"]="Пароль должен содержать хотя бы одну строчную букву (a-z)."
LANG_STRINGS["ru_install_caddy_password_number"]="Пароль должен содержать хотя бы одну цифру (0-9)."
LANG_STRINGS["ru_install_caddy_password_special"]="Пароль должен содержать хотя бы один специальный символ (!, @, #, $, %, ^, &, *, -, +, =, ? и т.д.)."
LANG_STRINGS["ru_install_caddy_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_caddy_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnawave-install-full
LANG_STRINGS["en_install_full_detected"]="Remnawave installation detected"
LANG_STRINGS["en_install_full_reinstall"]="Reinstall Remnawave? (y/n):"
LANG_STRINGS["en_install_full_stopping"]="Stopping and removing existing installation..."
LANG_STRINGS["en_install_full_reinstall_denied"]="Remnawave reinstallation denied"
LANG_STRINGS["en_install_full_subscription_detected"]="Subscription page installation detected"
LANG_STRINGS["en_install_full_subscription_reinstall"]="Reinstall subscription page? (y/n):"
LANG_STRINGS["en_install_full_subscription_reinstall_denied"]="Subscription page reinstallation denied"
LANG_STRINGS["en_install_full_caddy_detected"]="Caddy installation detected"
LANG_STRINGS["en_install_full_caddy_reinstall"]="Reinstall Caddy? (y/n):"
LANG_STRINGS["en_install_full_caddy_reinstall_denied"]="Caddy reinstallation denied"
LANG_STRINGS["en_install_full_no_components"]="No components to install"
LANG_STRINGS["en_install_full_need_protection"]="Do you need panel protection with custom path (Without protection /api/* and /api/sub/*)? (y/n):"
LANG_STRINGS["en_install_full_enter_panel_domain"]="Enter panel domain (e.g., panel.domain.com):"
LANG_STRINGS["en_install_full_domain_empty"]="Panel domain cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_enter_sub_domain"]="Enter subscription domain (e.g., sub.domain.com):"
LANG_STRINGS["en_install_full_enter_panel_port"]="Enter panel port (default 3000):"
LANG_STRINGS["en_install_full_enter_sub_port"]="Enter subscription port (default 3010):"
LANG_STRINGS["en_install_full_enter_project_name"]="Enter project name:"
LANG_STRINGS["en_install_full_project_name_empty"]="Project name cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_enter_project_description"]="Enter subscription page description:"
LANG_STRINGS["en_install_full_project_description_empty"]="Project description cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_enter_login_route"]="Enter panel access path (e.g., supersecretroute):"
LANG_STRINGS["en_install_full_login_route_empty"]="Panel access path cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_enter_admin_login"]="Enter administrator login:"
LANG_STRINGS["en_install_full_admin_login_empty"]="Administrator login cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_enter_admin_email"]="Enter administrator email:"
LANG_STRINGS["en_install_full_admin_email_empty"]="Administrator email cannot be empty. Please enter a value."
LANG_STRINGS["en_install_full_enter_admin_password"]="Enter administrator password (min. 8 characters, at least one uppercase, lowercase, number and special character):"
LANG_STRINGS["en_install_full_password_short"]="Password too short! Minimum 8 characters."
LANG_STRINGS["en_install_full_password_uppercase"]="Password must contain at least one uppercase letter (A-Z)."
LANG_STRINGS["en_install_full_password_lowercase"]="Password must contain at least one lowercase letter (a-z)."
LANG_STRINGS["en_install_full_password_number"]="Password must contain at least one number (0-9)."
LANG_STRINGS["en_install_full_password_special"]="Password must contain at least one special character (!, @, #, $, %, ^, &, *, -, +, =, ? etc.)."
LANG_STRINGS["en_install_full_installing"]="Installing Remnawave..."
LANG_STRINGS["en_install_full_installing_with_protection"]="Installing Remnawave with protection..."
LANG_STRINGS["en_install_full_installing_subscription"]="Installing subscription page..."
LANG_STRINGS["en_install_full_installing_subscription_with_protection"]="Installing subscription page with protection..."
LANG_STRINGS["en_install_full_installing_caddy"]="Installing Caddy..."
LANG_STRINGS["en_install_full_installing_caddy_with_protection"]="Installing Caddy with protection..."
LANG_STRINGS["en_install_full_docker_already_installed"]="Docker is already installed, skipping installation."
LANG_STRINGS["en_install_full_complete"]="Installation completed!"
LANG_STRINGS["en_install_full_press_key"]="Press any key to return to menu..."
LANG_STRINGS["en_install_full_please_enter_yn"]="Please enter only 'y' or 'n'"

LANG_STRINGS["ru_install_full_detected"]="Обнаружена установка Remnawave"
LANG_STRINGS["ru_install_full_reinstall"]="Переустановить Remnawave? (y/n):"
LANG_STRINGS["ru_install_full_stopping"]="Останавливаем и удаляем существующую установку..."
LANG_STRINGS["ru_install_full_reinstall_denied"]="Отказано в переустановке Remnawave"
LANG_STRINGS["ru_install_full_subscription_detected"]="Обнаружена установка страницы подписок"
LANG_STRINGS["ru_install_full_subscription_reinstall"]="Переустановить страницу подписок? (y/n):"
LANG_STRINGS["ru_install_full_subscription_reinstall_denied"]="Отказано в переустановке страницы подписок"
LANG_STRINGS["ru_install_full_caddy_detected"]="Обнаружена установка Caddy"
LANG_STRINGS["ru_install_full_caddy_reinstall"]="Переустановить Caddy? (y/n):"
LANG_STRINGS["ru_install_full_caddy_reinstall_denied"]="Отказано в переустановке Caddy"
LANG_STRINGS["ru_install_full_no_components"]="Нет компонентов для установки"
LANG_STRINGS["ru_install_full_need_protection"]="Требуется ли защита панели кастомным путем (Без защиты /api/* и /api/sub/*)? (y/n):"
LANG_STRINGS["ru_install_full_enter_panel_domain"]="Введите домен панели (например, panel.domain.com):"
LANG_STRINGS["ru_install_full_domain_empty"]="Домен панели не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_enter_sub_domain"]="Введите домен подписок (например, sub.domain.com):"
LANG_STRINGS["ru_install_full_enter_panel_port"]="Введите порт панели (по умолчанию 3000):"
LANG_STRINGS["ru_install_full_enter_sub_port"]="Введите порт подписок (по умолчанию 3010):"
LANG_STRINGS["ru_install_full_enter_project_name"]="Введите имя проекта:"
LANG_STRINGS["ru_install_full_project_name_empty"]="Имя проекта не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_enter_project_description"]="Введите описание страницы подписки:"
LANG_STRINGS["ru_install_full_project_description_empty"]="Описание проекта не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_enter_login_route"]="Введите путь доступа к панели (например, supersecretroute):"
LANG_STRINGS["ru_install_full_login_route_empty"]="Путь доступа к панели не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_enter_admin_login"]="Введите логин администратора:"
LANG_STRINGS["ru_install_full_admin_login_empty"]="Логин администратора не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_enter_admin_email"]="Введите email администратора:"
LANG_STRINGS["ru_install_full_admin_email_empty"]="Email администратора не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_full_enter_admin_password"]="Введите пароль администратора (мин. 8 символов, хотя бы одна заглавная, строчная, цифра и спецсимвол):"
LANG_STRINGS["ru_install_full_password_short"]="Пароль слишком короткий! Минимум 8 символов."
LANG_STRINGS["ru_install_full_password_uppercase"]="Пароль должен содержать хотя бы одну заглавную букву (A-Z)."
LANG_STRINGS["ru_install_full_password_lowercase"]="Пароль должен содержать хотя бы одну строчную букву (a-z)."
LANG_STRINGS["ru_install_full_password_number"]="Пароль должен содержать хотя бы одну цифру (0-9)."
LANG_STRINGS["ru_install_full_password_special"]="Пароль должен содержать хотя бы один специальный символ (!, @, #, $, %, ^, &, *, -, +, =, ? и т.д.)."
LANG_STRINGS["ru_install_full_installing"]="Установка Remnawave..."
LANG_STRINGS["ru_install_full_installing_with_protection"]="Установка Remnawave с защитой..."
LANG_STRINGS["ru_install_full_installing_subscription"]="Установка страницы подписок..."
LANG_STRINGS["ru_install_full_installing_subscription_with_protection"]="Установка страницы подписок с защитой..."
LANG_STRINGS["ru_install_full_installing_caddy"]="Установка Caddy..."
LANG_STRINGS["ru_install_full_installing_caddy_with_protection"]="Установка Caddy с защитой..."
LANG_STRINGS["ru_install_full_docker_already_installed"]="Docker уже установлен, пропускаем установку."
LANG_STRINGS["ru_install_full_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_full_press_key"]="Нажмите любую клавишу для возврата в меню..."
LANG_STRINGS["ru_install_full_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"

# Remnawave-install-panel
LANG_STRINGS["en_install_panel_detected"]="Remnawave installation detected"
LANG_STRINGS["en_install_panel_reinstall"]="Reinstall Remnawave? (y/n):"
LANG_STRINGS["en_install_panel_stopping"]="Stopping and removing existing installation..."
LANG_STRINGS["en_install_panel_reinstall_denied"]="Remnawave reinstallation denied"
LANG_STRINGS["en_install_panel_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_panel_installing"]="Installing Remnawave..."
LANG_STRINGS["en_install_panel_enter_panel_domain"]="Enter panel domain (e.g., panel.domain.com):"
LANG_STRINGS["en_install_panel_domain_empty"]="Panel domain cannot be empty. Please enter a value."
LANG_STRINGS["en_install_panel_enter_sub_domain"]="Enter subscription domain (e.g., sub.domain.com):"
LANG_STRINGS["en_install_panel_enter_panel_port"]="Enter panel port (default 3000):"
LANG_STRINGS["en_install_panel_docker_installed"]="Docker is already installed, skipping installation."
LANG_STRINGS["en_install_panel_installing_docker"]="Installing Docker..."
LANG_STRINGS["en_install_panel_complete"]="Installation completed!"
LANG_STRINGS["en_install_panel_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_panel_detected"]="Обнаружена установка Remnawave"
LANG_STRINGS["ru_install_panel_reinstall"]="Переустановить Remnawave? (y/n):"
LANG_STRINGS["ru_install_panel_stopping"]="Останавливаем и удаляем существующую установку..."
LANG_STRINGS["ru_install_panel_reinstall_denied"]="Отказано в переустановке Remnawave"
LANG_STRINGS["ru_install_panel_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_panel_installing"]="Установка Remnawave..."
LANG_STRINGS["ru_install_panel_enter_panel_domain"]="Введите домен панели (например, panel.domain.com):"
LANG_STRINGS["ru_install_panel_domain_empty"]="Домен панели не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_panel_enter_sub_domain"]="Введите домен подписок (например, sub.domain.com):"
LANG_STRINGS["ru_install_panel_enter_panel_port"]="Введите порт панели (по умолчанию 3000):"
LANG_STRINGS["ru_install_panel_docker_installed"]="Docker уже установлен, пропускаем установку."
LANG_STRINGS["ru_install_panel_installing_docker"]="Установка Docker..."
LANG_STRINGS["ru_install_panel_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_panel_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnawave-install-subscription
LANG_STRINGS["en_install_subscription_detected"]="Subscription page installation detected"
LANG_STRINGS["en_install_subscription_reinstall"]="Reinstall subscription page? (y/n):"
LANG_STRINGS["en_install_subscription_stopping"]="Stopping and removing existing installation..."
LANG_STRINGS["en_install_subscription_reinstall_denied"]="Subscription page reinstallation denied"
LANG_STRINGS["en_install_subscription_please_enter_yn"]="Please enter only 'y' or 'n'"
LANG_STRINGS["en_install_subscription_installing"]="Installing subscription page..."
LANG_STRINGS["en_install_subscription_enter_panel_domain"]="Enter panel domain (e.g., panel.domain.com):"
LANG_STRINGS["en_install_subscription_domain_empty"]="Panel domain cannot be empty. Please enter a value."
LANG_STRINGS["en_install_subscription_enter_sub_domain"]="Enter subscription domain (e.g., sub.domain.com):"
LANG_STRINGS["en_install_subscription_enter_sub_port"]="Enter subscription port (default 3010):"
LANG_STRINGS["en_install_subscription_enter_project_name"]="Enter project name:"
LANG_STRINGS["en_install_subscription_project_name_empty"]="Project name cannot be empty. Please enter a value."
LANG_STRINGS["en_install_subscription_enter_project_description"]="Enter subscription page description:"
LANG_STRINGS["en_install_subscription_project_description_empty"]="Project description cannot be empty. Please enter a value."
LANG_STRINGS["en_install_subscription_docker_installed"]="Docker is already installed, skipping installation."
LANG_STRINGS["en_install_subscription_installing_docker"]="Installing Docker..."
LANG_STRINGS["en_install_subscription_complete"]="Installation completed!"
LANG_STRINGS["en_install_subscription_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_install_subscription_detected"]="Обнаружена установка страницы подписок"
LANG_STRINGS["ru_install_subscription_reinstall"]="Переустановить страницу подписок? (y/n):"
LANG_STRINGS["ru_install_subscription_stopping"]="Останавливаем и удаляем существующую установку..."
LANG_STRINGS["ru_install_subscription_reinstall_denied"]="Отказано в переустановке страницы подписок"
LANG_STRINGS["ru_install_subscription_please_enter_yn"]="Пожалуйста, введите только 'y' или 'n'"
LANG_STRINGS["ru_install_subscription_installing"]="Установка страницы подписок..."
LANG_STRINGS["ru_install_subscription_enter_panel_domain"]="Введите домен панели (например, panel.domain.com):"
LANG_STRINGS["ru_install_subscription_domain_empty"]="Домен панели не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_subscription_enter_sub_domain"]="Введите домен подписок (например, sub.domain.com):"
LANG_STRINGS["ru_install_subscription_enter_sub_port"]="Введите порт подписок (по умолчанию 3010):"
LANG_STRINGS["ru_install_subscription_enter_project_name"]="Введите имя проекта:"
LANG_STRINGS["ru_install_subscription_project_name_empty"]="Имя проекта не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_subscription_enter_project_description"]="Введите описание страницы подписки:"
LANG_STRINGS["ru_install_subscription_project_description_empty"]="Описание проекта не может быть пустым. Пожалуйста, введите значение."
LANG_STRINGS["ru_install_subscription_docker_installed"]="Docker уже установлен, пропускаем установку."
LANG_STRINGS["ru_install_subscription_installing_docker"]="Установка Docker..."
LANG_STRINGS["ru_install_subscription_complete"]="Установка завершена!"
LANG_STRINGS["ru_install_subscription_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnawave-update-full
LANG_STRINGS["en_update_full_updating"]="Updating all components..."
LANG_STRINGS["en_update_full_complete"]="All components successfully updated!"
LANG_STRINGS["en_update_full_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_update_full_updating"]="Обновление всех компонентов..."
LANG_STRINGS["ru_update_full_complete"]="Все компоненты успешно обновлены!"
LANG_STRINGS["ru_update_full_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnawave-update-panel
LANG_STRINGS["en_update_panel_updating"]="Updating Remnawave..."
LANG_STRINGS["en_update_panel_complete"]="Remnawave successfully updated!"
LANG_STRINGS["en_update_panel_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_update_panel_updating"]="Обновление Remnawave..."
LANG_STRINGS["ru_update_panel_complete"]="Remnawave успешно обновлен!"
LANG_STRINGS["ru_update_panel_press_key"]="Нажмите любую клавишу для возврата в меню..."

# Remnawave-update-subscription
LANG_STRINGS["en_update_subscription_updating"]="Updating Subscription..."
LANG_STRINGS["en_update_subscription_complete"]="Subscription successfully updated!"
LANG_STRINGS["en_update_subscription_press_key"]="Press any key to return to menu..."

LANG_STRINGS["ru_update_subscription_updating"]="Обновление Subscription..."
LANG_STRINGS["ru_update_subscription_complete"]="Subscription успешно обновлен!"
LANG_STRINGS["ru_update_subscription_press_key"]="Нажмите любую клавишу для возврата в меню..."

# IPv6 Management
LANG_STRINGS["en_ipv6_menu"]="IPv6 Management Menu"
LANG_STRINGS["en_ipv6_status_enabled"]="IPv6 is currently ENABLED"
LANG_STRINGS["en_ipv6_status_disabled"]="IPv6 is currently DISABLED"
LANG_STRINGS["en_ipv6_disabling"]="Disabling IPv6..."
LANG_STRINGS["en_ipv6_enabling"]="Enabling IPv6..."
LANG_STRINGS["en_ipv6_disabled_success"]="IPv6 has been successfully disabled"
LANG_STRINGS["en_ipv6_enabled_success"]="IPv6 has been successfully enabled"
LANG_STRINGS["en_ipv6_already_disabled"]="IPv6 is already disabled"
LANG_STRINGS["en_ipv6_already_enabled"]="IPv6 is already enabled"
LANG_STRINGS["en_ipv6_disable_confirm"]="Do you want to disable IPv6? (y/n):"
LANG_STRINGS["en_ipv6_enable_confirm"]="Do you want to enable IPv6? (y/n):"
LANG_STRINGS["en_ipv6_operation_cancelled"]="Operation cancelled"

LANG_STRINGS["ru_ipv6_menu"]="Меню управления IPv6"
LANG_STRINGS["ru_ipv6_status_enabled"]="IPv6 в настоящее время ВКЛЮЧЕН"
LANG_STRINGS["ru_ipv6_status_disabled"]="IPv6 в настоящее время ОТКЛЮЧЕН"
LANG_STRINGS["ru_ipv6_disabling"]="Отключение IPv6..."
LANG_STRINGS["ru_ipv6_enabling"]="Включение IPv6..."
LANG_STRINGS["ru_ipv6_disabled_success"]="IPv6 успешно отключен"
LANG_STRINGS["ru_ipv6_enabled_success"]="IPv6 успешно включен"
LANG_STRINGS["ru_ipv6_already_disabled"]="IPv6 уже отключен"
LANG_STRINGS["ru_ipv6_already_enabled"]="IPv6 уже включен"
LANG_STRINGS["ru_ipv6_disable_confirm"]="Хотите отключить IPv6? (y/n):"
LANG_STRINGS["ru_ipv6_enable_confirm"]="Хотите включить IPv6? (y/n):"
LANG_STRINGS["ru_ipv6_operation_cancelled"]="Операция отменена"

get_string() {
    local key="$1"
    local lang_key="${LANGUAGE}_${key}"
    local string="${LANG_STRINGS[$lang_key]}"
    
    shift
    if [ $# -gt 0 ]; then
        printf "$string" "$@"
    else
        echo "$string"
    fi
}

select_language 